module.exports = Object.freeze({
	USER_ID: "userID",
	CURRENCY: "currency",
	JOB_ID: "jobID",
	JOB_LEVEL: "jobLevel",
	INTELLIGENCE: "intelligence",
	STRENGTH: "strength",
	LEVEL: "level",
	XP: "xp",
	INVENTORY: "inventory",
	STOCK: "stock",
	TOTAL_INCOME_THIS_WEEK: "totalIncomeThisWeek",
	EXPENSES_THIS_WEEK: "expensesThisWeek",
	IS_CLOCKED_IN: "isClockedIn",
	LAST_DAILY_CLAIMED: "lastDailyClaimed",
	DAILY_STREAK: "dailyStreak",
});
